# These are supported funding model platforms

github: [goralex97] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon:  goralexcomp # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: goralex97 # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: GORAlexComp/AppleColorEmojiFont # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://send.monobank.ua/fFFuoKtNC'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
